command:
  - streamlit
  - run
  - streamlit_app.py

env:
  - name: APP_ENVIRONMENT
    value: "prod"
  - name: QUERY_CACHE_TTL_SECONDS
    value: "600"
  - name: LAKEBASE_HOST
    value: "instance-09568850-8eda-42e6-870e-d8b6eceb87cd.database.azuredatabricks.net"
  - name: LAKEBASE_PORT
    value: "5432"
  - name: LAKEBASE_DATABASE
    value: "databricks_postgres"
